/**
 * THE THREE WHO STAYED
 *
 * Hand-authored, the same way the player is, against the same palette and the
 * same light. Nothing here is the player recoloured — a recoloured protagonist
 * is the exact placeholder look this settlement exists to avoid.
 *
 * They are built to be told apart at 480x270 before a word is read, by three
 * things at once:
 *
 *   silhouette      NAN is round, RUE is thin, ORRIN is square.
 *   motion          Nan is slow and rare, Rue is fast and never still,
 *                   Orrin barely moves at all.
 *   colour          Nan is cream and grey. Orrin is a dark apron over cream.
 *                   Rue has the only saturated garment in the valley — an
 *                   orange cap — and it is the first thing your eye finds.
 *
 * NAN is deliberately two pixels shorter than everyone else and her shawl is
 * two pixels wider than her own shoulders, which is what makes a small stooped
 * person instead of a short one.
 *
 * ORRIN's apron is the largest area of dark value on any character in the
 * game. At this size a beard plus a heavy apron is the whole character.
 *
 * RUE's body is eight pixels wide where the others are ten and twelve, and her
 * legs are drawn with a gap between them. Nobody else in Mosshollow has a gap.
 */

import type { PixelMap } from './pixel.ts';

// =============================================================================
// NAN HOLLIS — the one who stayed
// =============================================================================

export const NAN_DOWN_PASS: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kaassaak....',
  '....kaAAAAak....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kABBAk.....',
  '..kkNNNNNNNNkk..',
  '.kNNMMTTTTMMNNk.',
  '.kNMMdTTTTdMMNk.',
  '.kNMMdTTTTdMMNk.',
  '.kAMMdTTTTdMMAk.',
  '.kNMMdTTTTdMMNk.',
  '..kMMdTTTTdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '....kvvkkvvk....',
  '.....kk..kk.....',
];

export const NAN_DOWN_STEP_A: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kaassaak....',
  '....kaAAAAak....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kABBAk.....',
  '..kkNNNNNNNNkk..',
  '.kNNMMTTTTMMNNk.',
  '.kNMMdTTTTdMMNk.',
  '.kNMMdTTTTdMMNk.',
  '.kAMMdTTTTdMMAk.',
  '.kNMMdTTTTdMMNk.',
  '..kMMdTTTTdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '..kvvvk.kvvk....',
  '...kkk...kk.....',
];

export const NAN_DOWN_STEP_B: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kaassaak....',
  '....kaAAAAak....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kABBAk.....',
  '..kkNNNNNNNNkk..',
  '.kNNMMTTTTMMNNk.',
  '.kNMMdTTTTdMMNk.',
  '.kNMMdTTTTdMMNk.',
  '.kAMMdTTTTdMMAk.',
  '.kNMMdTTTTdMMNk.',
  '..kMMdTTTTdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '....kvvk.kvvvk..',
  '.....kk...kkk...',
];

export const NAN_SIDE_PASS: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....ksssssak....',
  '....kassssak....',
  '....kaAAAak.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kABBk......',
  '...kkNNNNNkk....',
  '..kNNMMTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMAk...',
  '..kNMMdTTTMNk...',
  '...kMMdTTTMk....',
  '...kTTTTTTk.....',
  '...kTTTTTTk.....',
  '...kYTTTTYk.....',
  '...kYYYYYYk.....',
  '...kvvvvk.......',
  '....kkkk........',
];

export const NAN_SIDE_STEP_A: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....ksssssak....',
  '....kassssak....',
  '....kaAAAak.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kABBk......',
  '...kkNNNNNkk....',
  '..kNNMMTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMAk...',
  '..kNMMdTTTMNk...',
  '...kMMdTTTMk....',
  '...kTTTTTTk.....',
  '...kTTTTTTk.....',
  '...kYTTTTYk.....',
  '..kYYYYYYYk.....',
  '..kvvk.kvvk.....',
  '...kk...kk......',
];

export const NAN_SIDE_STEP_B: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....ksssssak....',
  '....kassssak....',
  '....kaAAAak.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kABBk......',
  '...kkNNNNNkk....',
  '..kNNMMTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMAk...',
  '..kNMMdTTTMNk...',
  '...kMMdTTTMk....',
  '...kTTTTTTk.....',
  '...kTTTTTTk.....',
  '...kYTTTTYk.....',
  '...kYYYYYYk.....',
  '...kvvvvk.......',
  '....kkkk........',
];

export const NAN_UP_PASS: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kssssssk....',
  '....kassssak....',
  '....kassssak....',
  '....kaassak.....',
  '.....kaaak......',
  '.....kaaak......',
  '..kkNNNNNNNNkk..',
  '.kNNMMMMMMMMNNk.',
  '.kNMMdMMMMdMMNk.',
  '.kNMMdMMMMdMMNk.',
  '.kAMMdMMMMdMMAk.',
  '.kNMMdMMMMdMMNk.',
  '..kMMdMMMMdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '....kvvkkvvk....',
  '.....kk..kk.....',
];

export const NAN_UP_STEP_A: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kssssssk....',
  '....kassssak....',
  '....kassssak....',
  '....kaassak.....',
  '.....kaaak......',
  '.....kaaak......',
  '..kkNNNNNNNNkk..',
  '.kNNMMMMMMMMNNk.',
  '.kNMMdMMMMdMMNk.',
  '.kNMMdMMMMdMMNk.',
  '.kAMMdMMMMdMMAk.',
  '.kNMMdMMMMdMMNk.',
  '..kMMdMMMMdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '..kvvvk.kvvk....',
  '...kkk...kk.....',
];

export const NAN_UP_STEP_B: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kssssssk....',
  '....kassssak....',
  '....kassssak....',
  '....kaassak.....',
  '.....kaaak......',
  '.....kaaak......',
  '..kkNNNNNNNNkk..',
  '.kNNMMMMMMMMNNk.',
  '.kNMMdMMMMdMMNk.',
  '.kNMMdMMMMdMMNk.',
  '.kAMMdMMMMdMMAk.',
  '.kNMMdMMMMdMMNk.',
  '..kMMdMMMMdMMk..',
  '...kTTTTTTTTk...',
  '...kTTTTTTTTk...',
  '...kYTTTTTTYk...',
  '...kYYYYYYYYk...',
  '....kvvk.kvvvk..',
  '.....kk...kkk...',
];

/** Sweeping, facing away and down the step. Two frames, and the broom moves. */
export const NAN_SWEEP_A: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kssssssk....',
  '....kassssak....',
  '....kassssak....',
  '....kaassak.....',
  '.....kaaak......',
  '.....kaaak......',
  '..kkNNNNNNNNkk..',
  '.kNNMMMMMMMMNNk.',
  '.kNMMMMMMMMMMNk.',
  '.kNMMMMMMMMMAkc.',
  '.kAMMMMMMMMMMkc.',
  '.kNMMMMMMMMMNkc.',
  '..kMMMMMMMMMkc..',
  '...kTTTTTTTkc...',
  '...kTTTTTTkc....',
  '...kYTTTTYc.....',
  '...kYYYYYzzzk...',
  '....kvvkkzzzzk..',
  '.....kk..kzzzk..',
];

export const NAN_SWEEP_B: PixelMap = [
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....kssssssk....',
  '....kssssssk....',
  '....kassssak....',
  '....kassssak....',
  '....kaassak.....',
  '.....kaaak......',
  '.....kaaak......',
  '..kkNNNNNNNNkk..',
  '.kNNMMMMMMMMNNk.',
  '.kNMMMMMMMMMMNk.',
  '.kNMMMMMMMMMAk..',
  '.kAMMMMMMMMMMk..',
  '.kNMMMMMMMMMNkc.',
  '..kMMMMMMMMMkc..',
  '...kTTTTTTTkc...',
  '...kTTTTTTkc....',
  '...kYTTTTYc.....',
  '...kYYYYzzzk....',
  '....kvvzzzzk....',
  '.....kkzzzk.....',
];

/** On the bench, in the sun. */
export const NAN_SIT: PixelMap = [
  '................',
  '................',
  '................',
  '................',
  '.....kssssk.....',
  '....ksssssak....',
  '....kassssak....',
  '....kaAAAak.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kABBk......',
  '...kkNNNNNkk....',
  '..kNNMMTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMNk...',
  '..kNMMdTTTMAk...',
  '..kNMMdTTTMNk...',
  '...kMMdTTTMk....',
  '...kYTTTTTTTTk..',
  '...kYYYYYkvvvk..',
  '....kvvk..kkk...',
  '....kvvk........',
  '.....kk.........',
];

// =============================================================================
// RUE — the one who wants to go
// =============================================================================

export const RUE_DOWN_PASS: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJAAAAJk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kAAAAk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '...kA55555Ak....',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '....kcc..cck....',
  '....kcc..cck....',
  '....kvv..vvk....',
  '....kvv..vvk....',
  '....kkk..kkk....',
];

export const RUE_DOWN_STEP_A: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJAAAAJk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kAAAAk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '..kA455555k.....',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '...kcc...cck....',
  '...kcc....cck...',
  '...kvv....vvk...',
  '..kvvv....vvk...',
  '..kkkk....kkk...',
];

export const RUE_DOWN_STEP_B: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJAAAAJk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '.....kAAAAk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '.....k55555Ak...',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '....kcc...cck...',
  '...kcc....cck...',
  '...kvv....vvk...',
  '...kvv....vvvk..',
  '...kkk....kkkk..',
];

export const RUE_SIDE_PASS: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOOk....',
  '....kJJJJJJk....',
  '....kJAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kAAAk......',
  '.....k444k......',
  '....k44444k.....',
  '....k45554k.....',
  '....k45554k.....',
  '....k45555Ak....',
  '....k45554k.....',
  '....k45554k.....',
  '....k44444k.....',
  '....kccccck.....',
  '....kcccck......',
  '....kcccck......',
  '....kvvvk.......',
  '...kvvvvk.......',
  '...kkkkk........',
];

export const RUE_SIDE_STEP_A: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOOk....',
  '....kJJJJJJk....',
  '....kJAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kAAAk......',
  '.....k444k......',
  '....k44444k.....',
  '....k45554k.....',
  '...kA45554k.....',
  '....k45555k.....',
  '....k45554k.....',
  '....k45554k.....',
  '....k44444k.....',
  '....kccccck.....',
  '...kcc.cck......',
  '..kcc...cck.....',
  '..kvv...kvvk....',
  '..kvvk...kvvk...',
  '..kkk.....kkk...',
];

export const RUE_SIDE_STEP_B: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOOk....',
  '....kJJJJJJk....',
  '....kJAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '.....kAAAk......',
  '.....k444k......',
  '....k44444k.....',
  '....k45554k.....',
  '....k45554Ak....',
  '....k45555k.....',
  '....k45554k.....',
  '....k45554k.....',
  '....k44444k.....',
  '....kccccck.....',
  '....kcccck......',
  '...kcc.cck......',
  '...kvv.kvvk.....',
  '..kvvk..kvvk....',
  '..kkk....kkk....',
];

export const RUE_UP_PASS: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '.....kJJJJk.....',
  '.....kJJJJk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '...kA55555Ak....',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '....kcc..cck....',
  '....kcc..cck....',
  '....kvv..vvk....',
  '....kvv..vvk....',
  '....kkk..kkk....',
];

export const RUE_UP_STEP_A: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '.....kJJJJk.....',
  '.....kJJJJk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '..kA455555k.....',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '...kcc...cck....',
  '...kcc....cck...',
  '...kvv....vvk...',
  '..kvvv....vvk...',
  '..kkkk....kkk...',
];

export const RUE_UP_STEP_B: PixelMap = [
  '................',
  '.....kOOOOk.....',
  '....kOOOOOOk....',
  '....kIOOOOIk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '....kJJJJJJk....',
  '.....kJJJJk.....',
  '.....kJJJJk.....',
  '.....k4444k.....',
  '....k444444k....',
  '....k455554k....',
  '....k455554k....',
  '.....k55555Ak...',
  '....k455554k....',
  '....k455554k....',
  '....k444444k....',
  '....kcccccck....',
  '....kcc...cck...',
  '...kcc....cck...',
  '...kvv....vvk...',
  '...kvv....vvvk..',
  '...kkk....kkkk..',
];

/** Leaning on something, one ankle over the other. Her whole personality. */
export const RUE_LEAN: PixelMap = [
  '................',
  '......kOOOOk....',
  '.....kOOOOOOk...',
  '.....kIOOOOOk...',
  '.....kJJJJJJk...',
  '.....kJAAAAk....',
  '.....kAAAAAk....',
  '.....kAkAAAk....',
  '.....kABBBAk....',
  '......kAAAk.....',
  '......k444k.....',
  '.....k44444k....',
  '.....k45554k....',
  '....kA45554k....',
  '.....k45554k....',
  '.....k45554k....',
  '.....k44444k....',
  '.....kccccck....',
  '.....kcccck.....',
  '....kccckk......',
  '...kvvvk........',
  '..kvvvk.........',
  '..kvvk..........',
  '..kkk...........',
];

// =============================================================================
// ORRIN FELL — the one whose trade the valley no longer needs
// =============================================================================

export const ORRIN_DOWN_PASS: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAALk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '....kLBBBBLk....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNNccccccNNNk.',
  '.kNNccccccccNNk.',
  '.kNccccccccccNk.',
  '.kAccccGVccccAk.',
  '.kNccccccccccNk.',
  '.kNvccccccccvNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '..kEEE..EEEEk...',
  '..kEEE..EEEEk...',
  '..kvvv..vvvvk...',
  '..kvvv..vvvvk...',
  '..kkkk..kkkkk...',
];

export const ORRIN_DOWN_STEP_A: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAALk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '....kLBBBBLk....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNNccccccNNNk.',
  '.kNNccccccccNNk.',
  '.kNccccccccccNk.',
  '.kAccccGVccccAk.',
  '.kNccccccccccNk.',
  '.kNvccccccccvNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '.kEEE....EEEk...',
  '.kEEE.....EEk...',
  '.kvvv.....vvk...',
  'kvvvv.....vvk...',
  'kkkkk.....kkk...',
];

export const ORRIN_DOWN_STEP_B: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAALk....',
  '....kAAAAAAk....',
  '....kAkAAkAk....',
  '....kABBBBAk....',
  '....kLBBBBLk....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNNccccccNNNk.',
  '.kNNccccccccNNk.',
  '.kNccccccccccNk.',
  '.kAccccGVccccAk.',
  '.kNccccccccccNk.',
  '.kNvccccccccvNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '..kEEE....EEEk..',
  '..kEE.....EEEk..',
  '..kvv.....vvvk..',
  '..kvv.....vvvvk.',
  '..kkk.....kkkkk.',
];

export const ORRIN_SIDE_PASS: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '.....kLLk.......',
  '..kNNNNNNNNk....',
  '..kNNccccNNk....',
  '..kNccccccNk....',
  '..kNccccccck....',
  '..kNccGVcccAk...',
  '..kNccccccck....',
  '..kNvcccccck....',
  '..kNNvvvvvvk....',
  '...kEEEEEEk.....',
  '...kEEEEEk......',
  '...kEEEEk.......',
  '...kvvvk........',
  '..kvvvvk........',
  '..kkkkk.........',
];

export const ORRIN_SIDE_STEP_A: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '.....kLLk.......',
  '..kNNNNNNNNk....',
  '..kNNccccNNk....',
  '..kNccccccNk....',
  '..kNccccccck....',
  '..kNccGVcccAk...',
  '..kNccccccck....',
  '..kNvcccccck....',
  '..kNNvvvvvvk....',
  '...kEEEEEEk.....',
  '..kEE..EEEk.....',
  '.kEE....EEk.....',
  '.kvv....kvvk....',
  'kvvk.....kvvk...',
  'kkk.......kkk...',
];

export const ORRIN_SIDE_STEP_B: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '.....kLLk.......',
  '..kNNNNNNNNk....',
  '..kNNccccNNk....',
  '..kNccccccNk....',
  '..kNccccccck....',
  '..kNccGVcccAk...',
  '..kNccccccck....',
  '..kNvcccccck....',
  '..kNNvvvvvvk....',
  '...kEEEEEEk.....',
  '...kEEEEEk......',
  '..kEE..EEk......',
  '..kvv..kvvk.....',
  '.kvvk...kvvk....',
  '.kkk.....kkk....',
];

export const ORRIN_UP_PASS: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLJJJJLk....',
  '....kLLLLLLk....',
  '.....kLLLLk.....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNvNNNNNNvNNk.',
  '.kNNNvNNNNvNNNk.',
  '.kNNNNvNNvNNNNk.',
  '.kANNNNvvNNNNAk.',
  '.kNNNNvvvvNNNNk.',
  '.kNNNvvvvvvNNNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '..kEEE..EEEEk...',
  '..kEEE..EEEEk...',
  '..kvvv..vvvvk...',
  '..kvvv..vvvvk...',
  '..kkkk..kkkkk...',
];

export const ORRIN_UP_STEP_A: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLJJJJLk....',
  '....kLLLLLLk....',
  '.....kLLLLk.....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNvNNNNNNvNNk.',
  '.kNNNvNNNNvNNNk.',
  '.kNNNNvNNvNNNNk.',
  '.kANNNNvvNNNNAk.',
  '.kNNNNvvvvNNNNk.',
  '.kNNNvvvvvvNNNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '.kEEE....EEEk...',
  '.kEEE.....EEk...',
  '.kvvv.....vvk...',
  'kvvvv.....vvk...',
  'kkkkk.....kkk...',
];

export const ORRIN_UP_STEP_B: PixelMap = [
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLJJJJLk....',
  '....kLLLLLLk....',
  '.....kLLLLk.....',
  '.....kLLLLk.....',
  '.kNNNNNNNNNNNNk.',
  '.kNNvNNNNNNvNNk.',
  '.kNNNvNNNNvNNNk.',
  '.kNNNNvNNvNNNNk.',
  '.kANNNNvvNNNNAk.',
  '.kNNNNvvvvNNNNk.',
  '.kNNNvvvvvvNNNk.',
  '.kNNvvvvvvvvNNk.',
  '..kEEEEEEEEEk...',
  '..kEEE....EEEk..',
  '..kEE.....EEEk..',
  '..kvv.....vvvk..',
  '..kvv.....vvvvk.',
  '..kkk.....kkkkk.',
];

/**
 * At the bench, bent over the work. Two frames: the shoulders drop and the
 * hands come down. Nearly nothing moves, which is exactly right for him — the
 * whole read is that he is absorbed.
 */
export const ORRIN_WORK_A: PixelMap = [
  '................',
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '.....kLLk.......',
  '..kNNNNNNNNk....',
  '..kNNccccNNk....',
  '..kNccccccNk....',
  '..kNccccccck....',
  '..kNccGVcccAk...',
  '..kNccccccck....',
  '..kNvcccccck....',
  '..kNNvvvvvvk....',
  '...kEEEEEEk.....',
  '...kEEEEEk......',
  '...kEEEEk.......',
  '...kvvvk........',
  '..kvvvvk........',
  '..kkkkk.........',
];

export const ORRIN_WORK_B: PixelMap = [
  '................',
  '................',
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '..kNNNLLkNNk....',
  '..kNccccccNk....',
  '..kNccccccck....',
  '..kNcccccccAk...',
  '..kNccGVccAk....',
  '..kNccccccck....',
  '..kNvccccccck...',
  '..kNNvvvvvvk....',
  '...kEEEEEEk.....',
  '...kEEEEEk......',
  '...kEEEEk.......',
  '...kvvvk........',
  '..kvvvvk........',
  '..kkkkk.........',
];

/** On his own step, at noon. */
export const ORRIN_SIT: PixelMap = [
  '................',
  '................',
  '................',
  '.....kLLLLk.....',
  '....kLLLLLLk....',
  '....kLJJJJLk....',
  '....kLAAAAk.....',
  '....kAkAAAk.....',
  '....kABBBAk.....',
  '....kLBBBk......',
  '.....kLLk.......',
  '..kNNNNNNNNk....',
  '..kNccccccNk....',
  '..kNcccccccAk...',
  '..kNccGVccck....',
  '..kNccccccck....',
  '..kNNvvvvvvk....',
  '..kEEEEEEEEEk...',
  '..kEEEEEEEEEEk..',
  '..kvvvkEEEEEEk..',
  '..kkkk.kvvvvvk..',
  '........kkkkk...',
  '................',
  '................',
];
